#!/bin/bash

declare -r INPUT_FILE="${1:?input file is required!}"

cat "${INPUT_FILE}" \
	| sed -E 's/ *\| */\n/g' \
	| sed -E 's/^(sudo|nohup) +//' \
	| cut -d ' ' -f 1 \
	| sed -E 's/^.*\///' \
	| grep -E -v '^(ll|ls|cd|cat|vim|echo)$' \
	| awk '{total++; cmds[$1]++;} END{for (cmd in cmds) { print"%d %f %s\n", cmds[cmd], cmds[cmd]/total*100, cmd; }}' \
	| sort \
	| uniq -c \
	| sort -nr \
	|head -n 10 \
	|awk '{printf "%4d %6.2f%%  %s\n", $1,$2,$3;}'


